accelerator: "gpu"
torch_matmul_precision: "high"
num_workers: 10
mlflow_local_tracking_uri: "sqlite:///mlflow.db"
precision: "16-mixed"  # Use "bf16-mixed" if on A100/H100/RTX3090+ (this triggers GradScaler & autocast)
